name: CI/CD Pipeline

on: 
 push:
   branches:
    - main
jobs:
build-and-deploy:
   runs_on: ubuntu_latest
   steps:
   - name: Checkout code
     uses: actions/checkout@v3

   - name: Build Docker Image
     run: docker build -t static-website:1.0 .

   - name: Push Docker Image to Docker hub
     run: |
       echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME
       docker tag static-website:1.0 sushmitha1995/static-website:1.0
       docker push sushmitha1995/static-website:1.0

